---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cli
  labels:
    app: cli
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: cli
  template:
    metadata:
      labels:
        app: cli
    spec:
      containers:
        - name: dnsutils
          image: amouat/network-utils
          workingDir: /var/hyperledger/
          command:
            - "sh"
            - "-c"
            - "sleep 1000000000"
        - name: tools
          image: hyperledger/fabric-tools:1.4
          workingDir: /var/hyperledger/
          command:
            - "sh"
            - "-c"
            - "sleep 1000000000"
          volumeMounts:
            - name: data
              mountPath: /var/hyperledger/
        - name: ca
          image: hyperledger/fabric-ca:1.4
          workingDir: /var/hyperledger/
          command:
            - "sh"
            - "-c"
            - "sleep 1000000000"
          volumeMounts:
            - name: data
              mountPath: /var/hyperledger/
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: cli-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cli-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
