apiVersion: v1
kind: ConfigMap
metadata:
  name: peer-base-env
  namespace: testnet
data:
  CORE_VM_ENDPOINT: unix:///host/var/run/docker.sock
  FABRIC_LOGGING_SPEC: INFO
  CORE_PEER_TLS_ENABLED: "true"
  CORE_PEER_GOSSIP_USELEADERELECTION: "true"
  CORE_PEER_GOSSIP_ORGLEADER: "false"
  CORE_PEER_PROFILE_ENABLED: "true"
  CORE_PEER_TLS_CERT_FILE: /etc/hyperledger/fabric/tls/server.crt
  CORE_PEER_TLS_KEY_FILE: /etc/hyperledger/fabric/tls/server.key
  CORE_PEER_TLS_ROOTCERT_FILE: /etc/hyperledger/fabric/tls/ca.crt
  CORE_PEER_LISTENADDRESS: 0.0.0.0:7051
  CORE_PEER_CHAINCODELISTENADDRESS: 0.0.0.0:7052
